### ISSUE TITLE
How do i reference other class in the game process

### ISSUE THREAD

**Issue by Kahdeg-15520487** [bruhmoment21/cs2-sdk#10]
the one from here [https://github.com/neverlosecc/source2sdk/tree/cs2](https://github.com/neverlosecc/source2sdk/tree/cs2)

**Comment by bruhmoment21** [comment]
why?

**Comment by Kahdeg-15520487** [comment]
I want to made a skin changer and i can't find the member method in the src currently (according to this https://www.unknowncheats.me/forum/3711351-post132.html) , i'm new to this so if there is already a way to get the needed weapon service, please show me how

Grab the weapon services instance of your local player pawn: C_BasePlayerPawn::m_pWeaponServices.

Loop CPlayer_WeaponServices::m_hMyWeapons (num weapons is at + 0x0, data is at + 0x8).

**Comment by bruhmoment21** [comment]
see cbaseentity.hpp or another hpp file from that directory maybe youll get an idea

**Comment by Kahdeg-15520487** [comment]
i'm new to c++ so please bear with me.
as i understand, i need to use NETVAR to declared some kind of reference to the actual method signature in the main game process.
but when i then add another normal method, it's error'ed out
![image](https://user-images.githubusercontent.com/15503419/229134347-d920fa09-bf25-497d-abb5-b881299367df.png)

**Comment by bruhmoment21** [comment]
the NETVAR define is in netvars.hpp

**Comment by Kahdeg-15520487** [comment]
one more question, how do i set value to the NETVAR mapped property?
