### ISSUE TITLE
SDL_syswm.h

### ISSUE THREAD

**Issue by StrawberryKiwi12** [bruhmoment21/cs2-sdk#101]
Hey tried to compile on linux put was given 
fatal error: SDL3/SDL_syswm.h: No such file or directory
40 | #include <SDL3/SDL_syswm.h>

I am hoping this 
https://discourse.libsdl.org/t/sdl-sdl-syswm-h-has-been-removed-and-replaced-with-window-properties/47246
isn t the issue and I just didn't install sdl3 correctly

**Comment by bruhmoment21** [comment]
what distro are you using?

**Comment by StrawberryKiwi12** [comment]
Arch

**Comment by bruhmoment21** [comment]
clone [this](https://aur.archlinux.org/packages/sdl3-git)
cd sdl3-git && makepkg -si

and that should install sdl3 correctly

**Comment by StrawberryKiwi12** [comment]
Followed your directions and I am still popping the error

**Comment by bruhmoment21** [comment]
how are you building my project?

**Comment by StrawberryKiwi12** [comment]
Cloned it
cd into, then

```
cmake .
```
then

```
make
```

**Comment by bruhmoment21** [comment]
i don't thhink there's something that can be done. either you wait for imgui to be updated or you install an older sdl3 version

**Comment by StrawberryKiwi12** [comment]
All good, no worries, thank you for the code base

**Comment by bruhmoment21** [comment]
thanks! [maybe stalking this issue could help](https://github.com/ocornut/imgui/issues/7000)
