### ISSUE TITLE
How build it on linux?

### ISSUE THREAD

**Issue by tr0u8le** [bruhmoment21/cs2-sdk#104]
![bez nazwy](https://github.com/bruhmoment21/cs2-sdk/assets/130109122/abfb269c-a53e-440c-892e-45380ab478b1)

**Comment by bruhmoment21** [comment]
You will have to build sdl3 since on arch you cant "pacman -S sdl3" and im assuming you cant on your distro neither. after you've built sdl3 sucessfully you ll see a SDL_syswm.h warning. I will look into it when i can since ocornut pushed a fix for imgui recently

**Comment by tr0u8le** [comment]
Yep   #include <SDL3/SDL_syswm.h> error :/

**Comment by KGAT1W** [comment]
> Yep #include <SDL3/SDL_syswm.h> error :/

https://aur.archlinux.org/packages/sdl3-git

**Comment by KGAT1W** [comment]
![image](https://github.com/bruhmoment21/cs2-sdk/assets/99614510/ef9d88d2-3839-4c69-a3b0-85ef2c6f53fb)
how to fix

**Comment by KGAT1W** [comment]
> ![image](https://user-images.githubusercontent.com/99614510/285329147-ef9d88d2-3839-4c69-a3b0-85ef2c6f53fb.png) how to fix
For Vulkan application development, [install](https://wiki.archlinux.org/title/Install) [vulkan-headers]

**Comment by KGAT1W** [comment]
Have a fix ?

**Comment by bruhmoment21** [comment]
should be fixed

**Comment by snipcola** [comment]
On arch, the following resolved the issue for me:
`yay -S --noconfirm sdl3-git`
