### ISSUE TITLE
ESP Not work on last game version

### ISSUE THREAD

**Issue by SandFoxy** [bruhmoment21/cs2-sdk#11]

**Comment by bruhmoment21** [comment]
where have you downloaded it from

**Comment by DavinciPG** [comment]
@bruhmoment21 where you did worldtoscreen, that didn't seem to work for me, it wasnt getting world to screen correctly. I switched to this and esp renders fine now for me.

`
bool math::WorldToScreen(const Vector& in, Vector& out) {
    if (memory::fnScreenTransform(in, out)) return false;

	const ImVec2 vecDisplaySize = ImGui::GetIO().DisplaySize;
	out.x = (vecDisplaySize.x * 0.5f) + (out.x * vecDisplaySize.x) * 0.5f;
	out.y = (vecDisplaySize.y * 0.5f) - (out.y * vecDisplaySize.y) * 0.5f;
	return true;
}
`

**Comment by bruhmoment21** [comment]
> @bruhmoment21 where you did worldtoscreen, that didn't seem to work for me, it wasnt getting world to screen correctly. I switched to this and esp renders fine now for me.
> 
> `bool math::WorldToScreen(const Vector& in, Vector& out) { if (memory::fnScreenTransform(in, out)) return false;
> 
> ```
> const ImVec2 vecDisplaySize = ImGui::GetIO().DisplaySize;
> out.x = (vecDisplaySize.x * 0.5f) + (out.x * vecDisplaySize.x) * 0.5f;
> out.y = (vecDisplaySize.y * 0.5f) - (out.y * vecDisplaySize.y) * 0.5f;
> return true;
> ```
> 
> }`

does this work for you? i forgot to simplify the world2screen function
```
#include "math.hpp"

#include "../memory/memory.hpp"

#define IMGUI_DEFINE_MATH_OPERATORS
#include <imgui/imgui.h>

bool math::WorldToScreen(const Vector& in, Vector& out) {
    if (memory::fnScreenTransform(in, out)) return false;

    const ImVec2 screenHalvedSize = ImGui::GetIO().DisplaySize * 0.5f;

    out.x = screenHalvedSize.x * (1 + out.x);
    out.y = screenHalvedSize.y * (1 - out.y);

    return true;
}
```
