### ISSUE TITLE
Problem in the game when hooking createmove

### ISSUE THREAD

**Issue by unknownguy1993** [bruhmoment21/cs2-sdk#117]
```cpp
// Your code here
static CHook g_CreateMove;

static void hkCreateMove(CCSGOInput* input, const std::int32_t slot, const bool active) {
g_CreateMove.CallOriginal<void>(input, slot, active);
}

g_CreateMove.VHook(CCSGOInput::Get(), 5, SDK_HOOK(hkCreateMove));
```

When I enter a local game it generates a problem that I run too fast, I can't move sometimes, I fly around the map, I really don't know what I'm doing wrong or if there really is an external problem that is generating this.

**Comment by bruhmoment21** [comment]
i think 5 is an outdated index. this is how the 6th virtual function of csgoinput looks like so what i am guessing is that you are not hooking the correct function. try removing the third argument `const bool active` and perhaps change the return type to void*

![image](https://github.com/bruhmoment21/cs2-sdk/assets/53657322/b5934a40-478c-45a6-a156-8eaa25da603a)

**Comment by unknownguy1993** [comment]
great! thanks a lot you are a good guy!
