### ISSUE TITLE
cache and esp isn't working after 2/6/2024

### ISSUE THREAD

**Issue by master-of-darkness** [bruhmoment21/cs2-sdk#123]
Probably, hkOnAddEntity and hkOnRemoveEntity were broken after an update.

upd: my bad, everything is fine with hkOnAddEntity and hkOnRemoveEntity but esp still doesn't work

**Comment by clauadv** [comment]
change [this](https://github.com/bruhmoment21/cs2-sdk/blob/v2/cs2-sdk/sdk/src/bindings/entityinstance.cpp#L11) to 36
