### ISSUE TITLE
skinchanger

### ISSUE THREAD

**Issue by Haertas** [bruhmoment21/cs2-sdk#15]
![2023-04-02_16-04-26](https://user-images.githubusercontent.com/119797027/229332463-b2538baa-67f4-4581-9d44-12f6a228d920.png)

**Comment by bruhmoment21** [comment]
https://github.com/bruhmoment21/cs2-sdk/blob/39edbbe1849df351df6f851c3f5dfcbee4d0e546/cs2cheat/src/game/skins/skin_changer.cpp#L10-L11
