### ISSUE TITLE
skinchager 

### ISSUE THREAD

**Issue by Haertas** [bruhmoment21/cs2-sdk#18]
I do not know how to create pull requests 
code : 
.cpp 
 
#include <unordered_map>

#include "skin_changer.hpp"

#include "../../sdk/interfaces/interfaces.hpp"

// More details:
// https://www.unknowncheats.me/forum/3715213-post352.html

// I know that skins are being applied wrong.
// Cause: https://www.unknowncheats.me/forum/3715116-post351.html

static const std::unordered_map<uint16_t, int32_t> g_skinsMap{
    {4, 38},    // Glock 18 | Fade
    {7, 302},   // AK47 | Vulcan
    {32, 260},  // P2000 | Ivory
    {61, 504},  // USP | Kill Confirmed
};

void skin_changer::Run() {
    // https://www.unknowncheats.me/forum/3711351-post132.html
    if (!interfaces::pEngine->IsInGame()) return;

   CCSPlayerController* pLocalPlayerController =
        interfaces::pEntitySystem->GetLocalPlayerController();
    if (!pLocalPlayerController) {
        return;
    }

    C_CSPlayerPawn* pLocalPawn =
        pLocalPlayerController->m_hPawn().Get<C_CSPlayerPawn>();
    if (!pLocalPawn) {
        return;
    }

    CPlayer_WeaponServices* pWeaponServices = pLocalPawn->m_pWeaponServices();
    if (!pWeaponServices) {
        return;
    }

    CNetworkUtlVectorBase<CHandle>* pWeapons = pWeaponServices->m_hMyWeapons();
    if (!pWeapons) {
        return;
    }

    for (size_t i = 0; i < pWeapons->size; ++i) {
        C_BasePlayerWeapon* pWeapon =
            pWeapons->pData[i].Get<C_BasePlayerWeapon>();
        if (!pWeapon) {
            continue;
        }

        C_AttributeContainer* pAttributeContainer =
            pWeapon->m_AttributeManager();
        if (!pAttributeContainer) {
            continue;
        }

        C_EconItemView* pEconItemView = pAttributeContainer->m_Item();
        if (!pEconItemView) {
            continue;
        }

        const auto skinEntry =
            g_skinsMap.find(pEconItemView->m_iItemDefinitionIndex());
        if (skinEntry == g_skinsMap.cend()) {
            continue;
        }

        // Set the skin
        pWeapon->m_nFallbackPaintKit() = skinEntry->second;
        // Reset the other skin-related values to default
        pEconItemView->m_iItemIDLow() = -1;
        pWeapon->m_flFallbackWear() = 0.0001f;
        pWeapon->m_nFallbackSeed() = 0;
    }
}

**Comment by bruhmoment21** [comment]
what did u do exactly?

**Comment by Haertas** [comment]
I apologize for my English: Optimizations and readability improvements, Adding curly brackets for all conditional operator blocks, Moving each conditional operation block to a separate line for better readability, Changing the search operation in std::map using the find() method to avoid searching for an element twice, Removing unnecessary null checks for pointers pWeapons and pAttributeContainer, since these values have already been checked before,Use const auto& for skinEntry to avoid copying the values of std::map elements.

**Comment by bruhmoment21** [comment]
not taking suggestions at this time

**Comment by Haertas** [comment]
okay, sorry, if I manage to make the skins overlap well, I will definitely give you the code
