### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by x1en** [bruhmoment21/cs2-sdk#21]
![image](https://user-images.githubusercontent.com/75277136/229569263-47668e97-14da-4751-974e-4f85fb940d10.png)
getting this error on load

**Comment by bruhmoment21** [comment]
attach to cs2
record yourself injecting
after the exception gets caught double click every function thats shown in the callstack(bottom right corner)
upload to streamlabs or youtube

**Comment by bruhmoment21** [comment]
is standard injection selected in settings ?
and does it work if you remove "cs2_imgui.dll" from that list completely?

**Comment by x1en** [comment]
> is standard injection selected in settings ? and does it work if you remove "cs2_imgui.dll" from that list completely?

yes, nothing will change, its disabled

**Comment by bruhmoment21** [comment]
does it work if you inject with process hacker

**Comment by bruhmoment21** [comment]
i will close this if no input is given

**Comment by x1en** [comment]
> does it work if you inject with process hacker

nothing changed

**Comment by bruhmoment21** [comment]
have no idea other than to comment out hkPresent1 and hkResizeBuffers1

**Comment by bruhmoment21** [comment]
will close if given no input
