### ISSUE TITLE
pLocalPlayerController always null

### ISSUE THREAD

**Issue by ninetails0** [bruhmoment21/cs2-sdk#24]
as the title says

**Comment by Zwiebelmettwurst** [comment]
Give more details.  What game version? What did you change?

**Comment by ninetails0** [comment]
Nothing changed, injects fine. Test build v. 2000063/13868

**Comment by bruhmoment21** [comment]
how do i see the game version and is pEntitySystem null?

**Comment by bruhmoment21** [comment]
what about now is it fixed?

**Comment by bruhmoment21** [comment]
will close if given no input
