### ISSUE TITLE
The DLL is generated but not displayed even after injection

### ISSUE THREAD

**Issue by GuanGuan0623** [bruhmoment21/cs2-sdk#27]
Listen directly to your build, then inject the DLL and do not implement imgui in CS2

**Comment by GuanGuan0623** [comment]
Got a file cs2cheat Debug x64.dll

**Comment by bruhmoment21** [comment]
screen record

**Comment by GuanGuan0623** [comment]
Thanks, it's done.But there is a problem, there are only a few skins? The rest need to set their own right

**Comment by bruhmoment21** [comment]
i fixed some of the skins ill fix the gloves and knives when i have time
