### ISSUE TITLE
Operational issues

### ISSUE THREAD

**Issue by GuanGuan0623** [bruhmoment21/cs2-sdk#28]
Can you tell me the specific IMGUI use, I can only use a single skin, I can't replace other skins

**Comment by bruhmoment21** [comment]
screen record your issues bruh i can t understand you

**Comment by GuanGuan0623** [comment]
![_Q___A2WP_J___0ZUCXV_RQ.png](https://img1.imgtp.com/2023/04/09/t50eonvr.png)

**Comment by bruhmoment21** [comment]
you have to click add selected item to into inventory and the meaning of print class layout is to print exposed classes layouts
