### ISSUE TITLE
render not working

### ISSUE THREAD

**Issue by simv0lofficial** [bruhmoment21/cs2-sdk#3]
g_pd3dRenderTarget always false xd
https://github.com/bruhmoment21/cs2-sdk/blob/main/cs2cheat/src/hooks/platform/win32/directx11_hook.cpp#L266

**Comment by bruhmoment21** [comment]
what happens in CreateRenderTarget?

**Comment by simv0lofficial** [comment]
> > g_pd3dRenderTarget always false xd https://github.com/bruhmoment21/cs2-sdk/blob/main/cs2cheat/src/hooks/platform/win32/directx11_hook.cpp#L266
> 
> are you on windows 11?

10, 21H2

**Comment by Gauxalot** [comment]
> > > g_pd3dRenderTarget always false xd https://github.com/bruhmoment21/cs2-sdk/blob/main/cs2cheat/src/hooks/platform/win32/directx11_hook.cpp#L266
> > 
> > 
> > are you on windows 11?
> 
> 10, 21H2

idk im getting the same error, im gonna change the hook library to minhook and see if it works

**Comment by bruhmoment21** [comment]
```
static void CreateRenderTarget(IDXGISwapChain* pSwapChain) {
    ID3D11Texture2D* pBackBuffer = NULL;
    auto hr = pSwapChain->GetBuffer(0, IID_PPV_ARGS(&pBackBuffer));
    LOG("pSwapChain->GetBuffer: %u\n", hr);
    if (pBackBuffer) {
        DXGI_SWAP_CHAIN_DESC sd;
        hr = pSwapChain->GetDesc(&sd);
        LOG("pSwapChain->GetDesc: %u\n", hr);

        D3D11_RENDER_TARGET_VIEW_DESC desc = {};
        desc.Format = static_cast<DXGI_FORMAT>(
            GetCorrectDXGIFormat(sd.BufferDesc.Format));
        desc.ViewDimension = D3D11_RTV_DIMENSION_TEXTURE2D;

        hr = g_pd3dDevice->CreateRenderTargetView(pBackBuffer, &desc,
                                                  &g_pd3dRenderTarget);
        LOG("g_pd3dDevice->CreateRenderTargetView: %u\n", hr);
        pBackBuffer->Release();
    }
}
```

**Comment by bruhmoment21** [comment]
> ![image](https://user-images.githubusercontent.com/53585642/228235563-0c85bb5e-5c1f-42e0-93fd-0ca9baca8f1f.png)

i cannot reproduce. are your gpu drivers old? whats ur gpu?

**Comment by bruhmoment21** [comment]
fixed it https://github.com/bruhmoment21/cs2-sdk/commit/873cb0588ffee4893b3fb8e066677426223c0099 
does not happen for me no more
open if still persists
