### ISSUE TITLE
skins Question

### ISSUE THREAD

**Issue by GuanGuan0623** [bruhmoment21/cs2-sdk#31]
![1681101786303.jpg](https://img1.imgtp.com/2023/04/10/JOVU2gdk.jpg)
![1681101809654.jpg](https://img1.imgtp.com/2023/04/10/6UOeZSrO.jpg)
![1681101866172.jpg](https://img1.imgtp.com/2023/04/10/538Sno7k.jpg)

The warehouse can choose the skin, in the room does not show the skin
I'm here to bother you again, sorry

**Comment by bruhmoment21** [comment]
show ss of menu

**Comment by GuanGuan0623** [comment]
I clicked on ADD ALL ITEMS and after the warehouse had skin, it was replaced in the game but not displayed

**Comment by bruhmoment21** [comment]
download the latest version bruh i been told u 3 times already

**Comment by GuanGuan0623** [comment]
This is the latest version, I have removed the box

**Comment by GuanGuan0623** [comment]
Sorry brother, I didn't see your update 4 hours ago. I will test it after 12:00 Beijing time. Thank you, my good brother
