### ISSUE TITLE
hello, can you help me with inventory changer?

### ISSUE THREAD

**Issue by tesla15** [bruhmoment21/cs2-sdk#33]
if yes, contact me at tesla#1044

thank you so much

**Comment by bruhmoment21** [comment]
tell me mors so i know whats up

**Comment by tesla15** [comment]
im trying to fix inventory changer in oversee-csgo.
currently im at CreateEconItemsignature and AddEconItem

i got them like this
CreateEconItem 55 8B EC 83 EC 1C 8D 45 E4 C7 45 + 0x14
AddEconItem E8 ? ? ? ? 84 C0 74 E7

**Comment by tesla15** [comment]
this is how callstack looks like
![image](https://user-images.githubusercontent.com/117595540/231578948-ce63b7b8-880c-4b9e-8c79-d148da238699.png)
![image](https://user-images.githubusercontent.com/117595540/231579003-3daabd4e-0607-4e0a-a82f-ffbf82bbaf00.png)

the source is here [click](https://github.com/current/oversee-csgo)

**Comment by bruhmoment21** [comment]
i don't offer support but i cann tell you sum. you dont need the AddEconItem func thats been round in the leaked sdks and shit u need to do what i have done in my base sinply crrate a sharedobjecteconitem or whatever its called add it to the typecache and call socreated like i had done
