### ISSUE TITLE
Game crashes while using gui on match

### ISSUE THREAD

**Issue by HyperNeonX** [bruhmoment21/cs2-sdk#35]
So I recently injected the .dll with Extreme Injector v3, while using the debug version of your source code, (I´ve compiled it myself on Visual Studio) it runs fine on the main menu but at the moment I use it on any match, it crashes, it used to only occur when using specifically the inventory changer, now it occurs in general. After it crashes it generates this file with the name: _"cs2_2023_0419_223207_0_accessviolation.mdmp"_ on bin\win64, if this file remains on the folder, the .dll doesnt work, if i delete it, it returns to normal. im not an expert on this, so any help? or any idea why this happens?

**Comment by bruhmoment21** [comment]
open the mdmp in vs and click run with mixed code. if it doesnt show debug info it means you have built it again since the crash

**Comment by HyperNeonX** [comment]
Ok this pops up:
![unknown_2023 04 20-02 14](https://user-images.githubusercontent.com/112649739/233264738-d10ead78-2787-4e0b-b7a2-ee9192b1db51.png)
translation: Unhandled exception in 0x00007FFB3BAF0689 (client.dll) in cs2mod_2023_0420_021223_0_accessviolation.mdmp: 0xC0000005: Access violation when reading location 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.

**Comment by HyperNeonX** [comment]
Also should mention, the game crashes whenever I switch weapons, not just when using the gui, now it occurs like it used to before

**Comment by bruhmoment21** [comment]
record yourself clicking all the functions in the callstack. give me the console log and are u injecting with load library?

**Comment by bruhmoment21** [comment]
why have you closed it this you fix it?

**Comment by bruhmoment21** [comment]
does the latest commit fix the issue?

**Comment by HyperNeonX** [comment]
Oh god, so sorry if i closed this i have no clue sometimes how do I use github lmao, im checking rn the latest commit

**Comment by HyperNeonX** [comment]
https://anonfiles.com/t6Q54fmdzc/stuff_zip

I think those are all the files

**Comment by bruhmoment21** [comment]
looks like you crashed in client.dll can you play few times again until you crash in the base dll?

**Comment by HyperNeonX** [comment]
> looks like you crashed in client.dll can you play few times again until you crash in the base dll in case that happens?

Wym? Should I play without injecting anything? Is that what you mean?

**Comment by bruhmoment21** [comment]
no. i meant inject again and send again if you crash in cs2cheat debug.dll

**Comment by HyperNeonX** [comment]
Oh, got it, give me a sec

**Comment by bruhmoment21** [comment]
i would also like to know your game version

**Comment by HyperNeonX** [comment]
"Build: 9640 (revision 7941244)"

**Comment by bruhmoment21** [comment]
that is a pretty old game version not supported by the sdk. ill keep this issue open until you find a newer game version to tell me if it works or not. i got `Build: 9652 (revision 7964241)`

**Comment by HyperNeonX** [comment]
Got it, i will keep you in touch

**Comment by HyperNeonX** [comment]
Finally I got it working, thanks for the help man
