### ISSUE TITLE
can you add class to get_local_player, not get_local_player_controller

### ISSUE THREAD

**Issue by Darkdog123** [bruhmoment21/cs2-sdk#37]
can you add class to get_local_player, not get_local_player_controller

**Comment by Zwiebelmettwurst** [comment]
What do you mean? You can cast from the controller or you can get the Pawn(-Class) by utilising the Class members. Do you even know what Class you want to use?
```
g_pLocalPlayerController = pEntitySystem->GetLocalPlayerController();
    if (!g_pLocalPlayerController) return;
    g_pLocalPlayerPawn =
        g_pLocalPlayerController->m_hPawn().Get<C_CSPlayerPawn>();
```

Just look around the class members and you will get to your destination.

**Comment by bruhmoment21** [comment]
as Zwiebelmettwurst said
