### ISSUE TITLE
can u give me your discord?

### ISSUE THREAD

**Issue by Darkdog123** [bruhmoment21/cs2-sdk#38]
could you pass me your discord to make a conversation easier and faster please?

**Comment by Zwiebelmettwurst** [comment]
I don't think that @bruhmoment21 wants to spoonfeed you. You don't seem to understand _why_ your recently posted code won't work. You are just blindly copying stuff from UC and you are not using these issues here as intended.

**Comment by bruhmoment21** [comment]
what you need help with?
