### ISSUE TITLE
CS2 new update

### ISSUE THREAD

**Issue by chrisKodehode** [bruhmoment21/cs2-sdk#40]
The game crashes after injecting on the newest released update 07/06/2023

Client Version: 47/13880 9720

**Comment by bruhmoment21** [comment]
i don't have the latest version can you share where have you downloaded it from

**Comment by chrisKodehode** [comment]
> 

https://oof.lv/custom/?page=custom&id=cs2 here^^

**Comment by bruhmoment21** [comment]
thank you i will look into what has changed and update the sdk

**Comment by chrisKodehode** [comment]
> thank you i will look into what has changed and update the sdk

No problem, thank you for doing this bro^^ would do it myself but still learning to code firstly :D

**Comment by bruhmoment21** [comment]
hmmm a lot of stuff has changed so i will have to invest some time into this. i may not be able to update it this week

**Comment by chrisKodehode** [comment]
> hmmm a lot of stuff has changed so i will have to invest some time into this. i may not be able to update it this week

Yeah, was a huge update but it's fine^^ take your time! won't be a new update in a while anyways

**Comment by bruhmoment21** [comment]
id like to know if you experience any other crashes ive pushed a commit right now on the dev branch

**Comment by chrisKodehode** [comment]
> id like to know if you experience any other crashes ive pushed a commit right now on the dev branch

Will do! if you are in their discord, you'll see that they've posted a few new updates sadly tho so it might not work rn

**Comment by chrisKodehode** [comment]
works now^^^thanks <3

**Comment by chrisKodehode** [comment]
> id like to know if you experience any other crashes ive pushed a commit right now on the dev branch

gloves is not working btw

**Comment by bruhmoment21** [comment]
stated in known issues
