### ISSUE TITLE
Game crash upon menu display

### ISSUE THREAD

**Issue by trucklover818** [bruhmoment21/cs2-sdk#41]
Hey, trying to use the sdk with the latest game version from oof.lv and latest repo version
I am able to inject with extreme injector but when hiting insert game crashes (also tried with process hacker)

Crashes on line 33 for access violation in menu.cpp
![image](https://github.com/bruhmoment21/cs2-sdk/assets/136205823/b383afcb-5532-498e-b5c1-9721f656509e)

I tried adding a check for non null pointer before getting sdl window, but crashes on the first frame on line 38 in render.cpp
![image](https://github.com/bruhmoment21/cs2-sdk/assets/136205823/016c4928-d024-41b1-87b6-db208c4e8940)

any clue?

**Comment by GSNotifications** [comment]
Most likely due to #40

**Comment by bruhmoment21** [comment]
https://github.com/bruhmoment21/cs2-sdk/tree/dev
you can try using this until i fully fix the sdk

**Comment by trucklover818** [comment]
youre right using dev works
thanks
