### ISSUE TITLE
CreateMove hooking?

### ISSUE THREAD

**Issue by BasicllyMaximqs** [bruhmoment21/cs2-sdk#45]
I'm pretty sure that CS2 also utilizes CreateMove for its movement, but i haven't seen any hook for this in this SDK so far.
Would be a nice improvement to the base:

I've tried using sig 
`#define CREATE_MOVE \
    CS2_SDK_SIG("48 8B C4 48 89 58 10 48 89 48")`
without any luck.

Edit:
hooking createmove off `g_CreateMove.HookVirtual(interfaces::pInputSystem, 5, HOOK_FUNCTION(hkCreateMove));`

hasn't been successful either, im getting "too short instructions" error message

**Comment by Wolfyyta** [comment]
you hooking it from InputSystem g, hook it from CInput (not in this source, you need to reverse it)

**Comment by bruhmoment21** [comment]
he's right you have to hook from CCSGOInput not  from CInputSystem. i don'tplan onto hooking createmove
