### ISSUE TITLE
Open cheat Main?

### ISSUE THREAD

**Issue by longbishou** [bruhmoment21/cs2-sdk#55]
how to open Main?

**Comment by longbishou** [comment]
I tried all the keys but it didn't work

**Comment by longbishou** [comment]
![test](https://github.com/bruhmoment21/cs2-sdk/assets/56575794/064bc318-3c80-4851-a780-31706a9bf5cf)

**Comment by longbishou** [comment]
off rtss main working but skin not work maybe  add to steam inventory?
offline version 
![屏幕截图(997)](https://github.com/bruhmoment21/cs2-sdk/assets/56575794/cba13083-9f85-4448-acae-0f83c60ee1ba)

**Comment by nullptr818** [comment]
I think it's outdated because nothing works. esp is not showing skin changer as well.

**Comment by longbishou** [comment]
> I think it's outdated because nothing works. esp is not showing skin changer as well.

keys ins open main but skin changer not works maybe add to steam inventory?

**Comment by bruhmoment21** [comment]
you have to open csgo and keep it in the background if you want cs2 inventory to work.


> I think it's outdated because nothing works. esp is not showing skin changer as well.

how is it not working? are you using the latest push and what cs2 version do you have?

**Comment by longbishou** [comment]
> you have to open csgo and keep it in the background if you want cs2 inventory to work.
> 
> > I think it's outdated because nothing works. esp is not showing skin changer as well.
> 
> how is it not working? are you using the latest push and what cs2 version do you have?

 7launcher cs2...

**Comment by longbishou** [comment]
maybe add sticker cheat?

**Comment by bruhmoment21** [comment]
copy and paste log from "status"
(enter status in console)

**Comment by nullptr818** [comment]
> 7launcher cs2

yup it's latest version of cs2 and like when I inject everything shows but features are not working.. I have no idea what's going on that's why I said outdated.

**Comment by longbishou** [comment]
> > 7launcher cs2
> 
> yup it's latest version of cs2 and like when I inject everything shows but features are not working.. I have no idea what's going on that's why I said outdated.

off RTSS otherwise imgui notworking

**Comment by nullptr818** [comment]
> 
how do I do that bro? cuz seems like I don't have that RTSS

**Comment by longbishou** [comment]
Maybe other overlays are interfering with IMGUI?
