### ISSUE TITLE
Can't inject

### ISSUE THREAD

**Issue by lisacek** [bruhmoment21/cs2-sdk#58]
Help please
![image](https://github.com/bruhmoment21/cs2-sdk/assets/49589605/a23fb0da-8041-4705-a744-8806d3bea356)
![image](https://github.com/bruhmoment21/cs2-sdk/assets/49589605/df0eceb9-589a-41f0-9031-c1aeea0c653d)

**Comment by silverwomper** [comment]
> Help please ![image](https://user-images.githubusercontent.com/49589605/265078991-a23fb0da-8041-4705-a744-8806d3bea356.png) ![image](https://user-images.githubusercontent.com/49589605/265078897-df0eceb9-589a-41f0-9031-c1aeea0c653d.png)

Use Manual + Wouldn't use right now because it will crash randomly due to a invalid vmt hk

**Comment by bruhmoment21** [comment]
manual map not supported
