### ISSUE TITLE
NOT WORK

### ISSUE THREAD

**Issue by ikategame** [bruhmoment21/cs2-sdk#6]
![image](https://user-images.githubusercontent.com/108955065/228363970-f6e81564-ae0c-4002-b263-7d4d90b97389.png)

**Comment by bruhmoment21** [comment]
hmmm thats interesting
can i get more info on whats happening?

**Comment by ikategame** [comment]
i injected with extreme injector manual map in cs2.exe and all settings are on low windowed mode

**Comment by bruhmoment21** [comment]
not meant to be injected with manual map
loadlibrary only (called standard injection in extreme injector).
