### ISSUE TITLE
crash problem

### ISSUE THREAD

**Issue by ucanke** [bruhmoment21/cs2-sdk#62]
Bro, cheat is crashing while entering a map. 
Game version : 13940. 
Can you say how i can fix ?

**Comment by maecry** [comment]
https://github.com/bruhmoment21/cs2-sdk/blob/3e81ce356585dd0dcf61f144d708c619e704c1c0/cs2cheat/src/sdk/source2-sdk/interfaces/cschemasystem.hpp#L30

`
  auto FindDeclaredClass(const char* pClass) {
        SchemaClassInfoData_t* ret = nullptr;
        CALL_VIRTUAL(void, 2, this, ret, pClass);
        return ret;
    }
`

https://github.com/bruhmoment21/cs2-sdk/blob/3e81ce356585dd0dcf61f144d708c619e704c1c0/cs2cheat/src/sdk/source2-sdk/entity/c_baseentity.cpp#L9
->144

https://github.com/bruhmoment21/cs2-sdk/blob/3e81ce356585dd0dcf61f144d708c619e704c1c0/cs2cheat/src/sdk/source2-sdk/entity/centityinstance.hpp#L10C9-L10C9
same with FindDeclaredClass(...) type it urself

idk any left but should be that to fix the crash

**Comment by ucanke** [comment]
Hello Bro, thanks for your reply.
But problem isnt fixed.
These screenshots are my debugs : 
https://prnt.sc/Qk4Z-HAUd2NJ
https://prnt.sc/xBdrLgv0R20z
https://prnt.sc/M1r8JDxeiByQ
https://prnt.sc/VOhwDUVShGSx
