### ISSUE TITLE
C:\Users\Павел\Downloads\cs2-sdk-1\cs2cheat\src\sdk\virtual.hpp

### ISSUE THREAD

**Issue by CMAULTOP** [bruhmoment21/cs2-sdk#71]
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	C2440	<function-style-cast>: невозможно преобразовать "initializer list" в "T"	cs2cheat	C:\Users\Павел\Downloads\cs2-sdk-1\cs2cheat\src\sdk\virtual.hpp	34

**Comment by simv0lofficial** [comment]
> Серьезность Код Описание Проект Файл Строка Состояние подавления Ошибка C2440 : невозможно преобразовать "initializer list" в "T" cs2cheat C:\Users\Павел\Downloads\cs2-sdk-1\cs2cheat\src\sdk\virtual.hpp 34

вижак иссуе

**Comment by KGAT1W** [comment]
Уважаемый Павел(Пашка) Иди ты
