### ISSUE TITLE
skins default + gui does nothing?

### ISSUE THREAD

**Issue by 0xjdfhdfsb** [bruhmoment21/cs2-sdk#74]
manual mapped the dll (using latest commit) and dumped / equipped some skins - went ingame and all skins are just displayed default in hand? also, the esp or literally anything i toggle / untoggle does nothing. so i can basically only unlock skins in the collection, but besides that, nothing works
thanks in advance for any assistance

**Comment by bruhmoment21** [comment]
manual map not supported only loadlibrary
