### ISSUE TITLE
Got banned huh

### ISSUE THREAD

**Issue by Julosss** [bruhmoment21/cs2-sdk#78]
To test this cheat I created a fresh account (without prime enabled) and got almost instantly banned (1 deathmatch game). I was not using any skinchanger, only esp (which didn't even work). I used AlisaAlis Manual Map DLL Injector for injection. Where lies the problem with detection? Will modifying code heavily change the outcome or do I have to use different injector/injection method?

**Comment by TookieBW** [comment]
its probalby the hook that is detected

**Comment by CrazyCSIW6** [comment]
Injecting via manual map doesn't work, use a thread hijacking method instead to avoid features not working.

**Comment by bruhmoment21** [comment]
i guess they ban instantly for bytepatching (hooking) and not lower your trust like they did in csgo. youll have to deal with the detection on your own

**Comment by Julosss** [comment]
Thank you for ideas

**Comment by tandanis** [comment]
I just tried minhook but still get dedects, are there anything to suggest for making it ud?
