### ISSUE TITLE
Not working in the latest CS2

### ISSUE THREAD

**Issue by Nep-Timeline** [bruhmoment21/cs2-sdk#80]
![image](https://github.com/bruhmoment21/cs2-sdk/assets/53483352/253a9eb3-0f62-4865-a820-a199d866a377)

**Comment by Valeedb** [comment]
The client works only with "-insecure"

**Comment by Nep-Timeline** [comment]
> The client works only with "-insecure"

I always using this command to start the game.

**Comment by Valeedb** [comment]
Just loaded it, seems to not work properly. Game updated prob
