### ISSUE TITLE
Update regarding the cheat - VAC BAN

### ISSUE THREAD

**Issue by ghost** [bruhmoment21/cs2-sdk#81]
Hey i strongly recommend a friend considering a shift to a more well-known hooking lib like Minhook when working with your base and cutting out anything else for more well known libraries. it offers a robust and reliable solution for your cheat compared to what is used now as you more then likely already know. 

outside of this after testing private and public injectors i have done extensive testing and come to the conclusion the cheat is vac detected as a direct result unfortunately.

**Comment by bruhmoment21** [comment]
How does that change anything? How does the hooking library matter? The only thing a hooking library does that can be detected is, well, hooking. The dissasembler doesn't write anything (bytepatch) so the only thing remaining is the hooking itself. MinHook and funchook both overwrite the beginning of the function you want to hook with a JMP followed by the relative address, so your whole point is invalid.

**Comment by ghost** [comment]
i meant to say "the cheat is vac detected as it stands unfortunately." From a technical standpoint on the hooking library matter, both MinHook and funchook are great and do utilize similar techniques by overwriting the beginning of a function with a JMP instruction followed by a relative address, this is a common method for redirecting code execution flow without modifying the original code obviously, to clarify, my intention was not to dismiss the base entirely because it's not using what's better known it was merely a recommendation i made poorly explained lol. It still serves as a solid foundation, being lightweight and simple, and it may be sufficient for less complex hooking tasks i guess, and its simplicity can be an advantage for some developers. However, if you need advanced features, reliability, and a larger support community, MinHook may be the better choice if you ever decide to change it  👍

**Comment by maecry** [comment]
is this AI generated?

**Comment by ghost** [comment]
> is this AI generated?

NO lol hahahah
