### ISSUE TITLE
new update today causes a crash on inject

### ISSUE THREAD

**Issue by BulletGG** [bruhmoment21/cs2-sdk#87]

**Comment by bruhmoment21** [comment]
is it still happening?

**Comment by jinxx0** [comment]
> is it still happening?

Yes

**Comment by bruhmoment21** [comment]
> > is it still happening?
> 
> Yes

are you using manual map? if then have you read the readme for using manual map

**Comment by jinxx0** [comment]
> > > is it still happening?
> > 
> > 
> > Yes
> 
> are you using manual map? if then have you read the readme for using manual map

Ok i fixed it using tutorial on read me
