### ISSUE TITLE
Inject error

### ISSUE THREAD

**Issue by lenorio** [bruhmoment21/cs2-sdk#89]
![image](https://github.com/bruhmoment21/cs2-sdk/assets/122083296/59c57608-0f2c-4c31-a655-5384ac146e93)
How to fix?
CS2 Crashes after inject and this window

**Comment by Abedbaydoun** [comment]
bro can u tell me how to inject it theres no dll in the files

**Comment by lenorio** [comment]
> bro can u tell me how to inject it theres no dll in the files

u need to build with using microsoft visual code

**Comment by bruhmoment21** [comment]
are you using load library? thats what this base supports

**Comment by l1nxxwrld** [comment]
> are you using load library? thats what this base supports

loadlibrary isn't supported in cs2 since it's getting blocked by cs

**Comment by bruhmoment21** [comment]
> > are you using load library? thats what this base supports
> 
> loadlibrary isn't supported in cs2 since it's getting blocked by cs

my only workaround for this is to inject before than this [function](https://github.com/bruhmoment21/cs2-sdk/assets/53657322/95342eee-4e0b-430e-ab19-a398089dd9aa) is called. it hooks NtOpenFile and thats the cause loadlibrary is not working.
`44 89 4C 24 ? 44 88 44 24 ? [in cs2.exe]`

low quality solution:
make your injector wait until cs2.exe pid can be retrieved (loop) and inject as quick as it gets.
extreme injector has auto inject but youll get banned some hours after.

**Comment by bruhmoment21** [comment]
read readme for manual map support
