### ISSUE TITLE
Maybe make the changer for gloves?

### ISSUE THREAD

**Issue by Cyk-Fad** [bruhmoment21/cs2-sdk#92]
Like the title.Inventory changer and skinchanger(knife/weapon) works perfectly.But the glove changer dose not work.
If you have time to make the function.That would be thankful!

**Comment by FrostOnAcid** [comment]
He stated clearly that he doesnt support the SkinChanger anymore and got rid of it. v1 is a perfect base which you can simply modify. Gloves are now in the Viewmodel. 
More Infos are in this UC Thread -> https://www.unknowncheats.me/forum/counter-strike-2-a/604003-change-gloves.html
