### ISSUE TITLE
pch.hpp not included

### ISSUE THREAD

**Issue by Dynamooo1** [bruhmoment21/cs2-sdk#94]
i going include pch and always say does included how to fix bro?

**Comment by Valeedb** [comment]
Configure the project settings.

**Comment by FrostOnAcid** [comment]
This is a precompiled header (pch.hpp) issue.

1. Ensure that pch.hpp is present in the project directory.
2. In Visual Studio, right-click on the project in Solution Explorer > Properties > Configuration Properties > C/C++ > Precompiled Headers. Make sure 'Precompiled Header' is set to 'Use (/Yu)' and 'Precompiled Header File' is pointing to pch.hpp.
3. If you're not using precompiled headers, you can set 'Precompiled Header' to 'Not Using Precompiled Headers' in the project properties.
4.  Make sure all the source files in your project that use the precompiled header include pch.hpp at the very top.

More Infos can be found here -> https://stackoverflow.com/questions/54121917/what-is-pch-h-and-why-is-it-needed-to-be-included-as-the-first-header-file
