### ISSUE TITLE
crashing manual map injector x64

### ISSUE THREAD

**Issue by Dynamooo1** [bruhmoment21/cs2-sdk#96]
hello bro i have problem with this cheat i going inject any x64 manual map injector and i got crash how to fix?

**Comment by bruhmoment21** [comment]
Manual map - `/Zc:threadSafeInit-` flag is required. C/C++ -> Command Line -> Additional Options.
 
 have you tried this?

**Comment by Dynamooo1** [comment]
yes i tried and does work

**Comment by bruhmoment21** [comment]
is there any crashing still happening?

**Comment by Dynamooo1** [comment]
insta crashing when i inject

**Comment by bruhmoment21** [comment]
record your screen building+injecting everything and also record  typing in the compiler flag

**Comment by Dynamooo1** [comment]
![image](https://github.com/bruhmoment21/cs2-sdk/assets/45859878/5f8ccd4c-2b6e-4f4c-a0aa-e7aa5ceb63da)

**Comment by Dynamooo1** [comment]
![image](https://github.com/bruhmoment21/cs2-sdk/assets/45859878/8504fceb-af9f-4c02-889b-9f4d784ef79c)
now i have this problem with compile

**Comment by bruhmoment21** [comment]
![image](https://github.com/bruhmoment21/cs2-sdk/assets/53657322/01f03e6e-f0ea-4458-a2af-2db5d5c123d1)
are you using visual studio 2022?

**Comment by Dynamooo1** [comment]
yes

**Comment by bruhmoment21** [comment]
extreme injector manual map works for me idk what the issue could be

**Comment by Dynamooo1** [comment]
i use dx cheat mapper manual map cheat injecting but does initialize in game

**Comment by Dynamooo1** [comment]
i use any injector and working initializing but my game does open

**Comment by Dynamooo1** [comment]
![image](https://github.com/bruhmoment21/cs2-sdk/assets/45859878/df8eec7b-533d-4a6d-a4d7-bdde5a386f34)
does open game
