### ISSUE TITLE
Adding a save/load configuration system?

### ISSUE THREAD

**Issue by itzMal** [bruhmoment21/cs2-sdk#98]
Hey brotha - I'm wanting to be able to create a save/loading system (more specifically for the inventory/skin changer in V1) and I am not too experienced with C++ - did some research but since I didn't create the code myself I'm not really sure how to go about this. Is this something you'd be able to help me with/add as a feature that works with both V1 and V2? Thanks man! Appreciate the work!

**Comment by bruhmoment21** [comment]
json is what you may be looking for. not looking forward into implementing a save/load system
